### PR TITLE
Tank V.1 

### PR DESCRIPTION
**Pull request by Rodhlann**
Directory for FBX objects as well as the base tank model I created.

### CODE REVIEW

**Comment by mynameismiek** [comment]
Is this scaled properly? https://wiki.unrealengine.com/Static_Mesh_from_Blender  
also, there is a /src/mesh folder now it should probably go in there. I put an empty blend file in there that has the scale set properly.

**Comment by mynameismiek** [comment]
also Failed to import '/Desktop/tank.fbx'. Failed to create asset '/Game/Meshes/tank'

**Comment by Rodhlann** [comment]
Just made those changes and gave you the Blend file for the tank. See if you can export it on your machine.

**Comment by mynameismiek** [comment]
need to translate it up so the bottom is at the origin in blender.

**Pull request merged**
